/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FlotaRouteImport } from './routes/flota'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FlotaRoute = FlotaRouteImport.update({
  id: '/flota',
  path: '/flota',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/flota': typeof FlotaRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/flota': typeof FlotaRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/flota': typeof FlotaRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/flota'
    | '/galeria'
    | '/nosotros'
    | '/proyectos'
    | '/servicios'
    | '/terminos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/flota'
    | '/galeria'
    | '/nosotros'
    | '/proyectos'
    | '/servicios'
    | '/terminos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/flota'
    | '/galeria'
    | '/nosotros'
    | '/proyectos'
    | '/servicios'
    | '/terminos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  FlotaRoute: typeof FlotaRoute
  GaleriaRoute: typeof GaleriaRoute
  NosotrosRoute: typeof NosotrosRoute
  ProyectosRoute: typeof ProyectosRoute
  ServiciosRoute: typeof ServiciosRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flota': {
      id: '/flota'
      path: '/flota'
      fullPath: '/flota'
      preLoaderRoute: typeof FlotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  FlotaRoute: FlotaRoute,
  GaleriaRoute: GaleriaRoute,
  NosotrosRoute: NosotrosRoute,
  ProyectosRoute: ProyectosRoute,
  ServiciosRoute: ServiciosRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
